In [1]:
import sys
print(sys.executable)

d:\Code and learning\E-commerce Sales Performance Dashboard\venv\Scripts\python.exe

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
# Load dataset
df = pd.read_excel("../data/raw/Online Retail.xlsx")

print("Dataset loaded successfully.")
df.head()

Dataset loaded successfully.

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
# Dataset shape
df.shape

(541909, 8)

In [5]:
# Column names
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [6]:
# Data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [7]:
# Missing values
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
# Duplicate rows
df.duplicated().sum()

np.int64(5268)

In [10]:
# Remove duplicate rows
df = df.drop_duplicates()

print("New shape after removing duplicates:", df.shape)

New shape after removing duplicates: (536641, 8)

In [11]:
# Missing values in Description
df["Description"].isnull().sum()

np.int64(1454)

In [12]:
# Remove rows with missing Description
df = df.dropna(subset=["Description"])

print("New shape after removing missing descriptions:", df.shape)

New shape after removing missing descriptions: (535187, 8)

In [13]:
# Invoices that start with "C" (cancelled/returned orders)
df[df["InvoiceNo"].astype(str).str.startswith("C")].shape

(9251, 8)

In [14]:
# Rows with negative quantity
df[df["Quantity"] < 0].shape

(9725, 8)

In [15]:
# Rows with zero quantity
df[df["Quantity"] == 0].shape

(0, 8)

In [16]:
# Rows with invalid UnitPrice
df[df["UnitPrice"] <= 0].shape

(1058, 8)

In [17]:
# Keep only valid sales transactions
df = df[
    (df["Quantity"] > 0) &
    (df["UnitPrice"] > 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C"))
]

print("Shape after removing returns/cancellations and invalid values:", df.shape)

Shape after removing returns/cancellations and invalid values: (524878, 8)

In [18]:
# Create TotalSales column
df["TotalSales"] = df["Quantity"] * df["UnitPrice"]

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [19]:
# Create date-related columns
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["MonthName"] = df["InvoiceDate"].dt.strftime("%B")
df["MonthYear"] = df["InvoiceDate"].dt.to_period("M").astype(str)

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales,Year,Month,MonthName,MonthYear
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,December,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,December,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,2010-12

In [20]:
# Check updated dataframe structure
df.info()

<class 'pandas.DataFrame'>
Index: 524878 entries, 0 to 541908
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    524878 non-null  object
 1   StockCode    524878 non-null  object
 2   Description  524878 non-null  object
 3   Quantity     524878 non-null  int64
 4   InvoiceDate  524878 non-null  datetime64[us]
 5   UnitPrice    524878 non-null  float64
 6   CustomerID   392692 non-null  float64
 7   Country      524878 non-null  str
 8   TotalSales   524878 non-null  float64
 9   Year         524878 non-null  int32
 10  Month        524878 non-null  int32
 11  MonthName    524878 non-null  str
 12  MonthYear    524878 non-null  str
dtypes: datetime64[us](1), float64(3), int32(2), int64(1), object(3), str(3)
memory usage: 52.1+ MB

In [21]:
# Preview cleaned and enriched dataset
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales,Year,Month,MonthName,MonthYear
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,December,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,December,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,2010-12

In [22]:
# Export cleaned dataset
df.to_csv("../data/processed/online_retail_cleaned.csv", index=False)

print("Cleaned dataset exported successfully.")

Cleaned dataset exported successfully.

In [23]:
# Create monthly summary by product
monthly_summary = df.groupby(["MonthYear", "Description"], as_index=False).agg({
    "Quantity": "sum",
    "UnitPrice": "mean",
    "TotalSales": "sum"
})

monthly_summary.rename(columns={
    "Quantity": "TotalQuantitySold",
    "UnitPrice": "AverageUnitPrice"
}, inplace=True)

monthly_summary.head()

,MonthYear,Description,TotalQuantitySold,AverageUnitPrice,TotalSales
0,2010-12,4 PURPLE FLOCK DINNER CANDLES,16,3.386667,45.82
1,2010-12,OVAL WALL MIRROR DIAMANTE,22,13.306250,283.03
2,2010-12,SET 2 TEA TOWELS I LOVE LONDON,306,3.710000,1006.94
3,2010-12,*Boombox Ipod Classic,1,16.980000,16.98
4,2010-12,*USB Office Mirror Ball,2,8.470000,16.94

In [24]:
# Export monthly summary
monthly_summary.to_csv("../data/processed/monthly_summary.csv", index=False)

print("Monthly summary exported successfully.")

Monthly summary exported successfully.

In [25]:
# Check monthly summary structure
monthly_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 33782 entries, 0 to 33781
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   MonthYear          33782 non-null  str
 1   Description        33782 non-null  str
 2   TotalQuantitySold  33782 non-null  int64
 3   AverageUnitPrice   33782 non-null  float64
 4   TotalSales         33782 non-null  float64
dtypes: float64(2), int64(1), str(2)
memory usage: 1.3 MB

In [26]:
monthly_summary.head(10)

,MonthYear,Description,TotalQuantitySold,AverageUnitPrice,TotalSales
0,2010-12,4 PURPLE FLOCK DINNER CANDLES,16,3.386667,45.82
1,2010-12,OVAL WALL MIRROR DIAMANTE,22,13.306250,283.03
2,2010-12,SET 2 TEA TOWELS I LOVE LONDON,306,3.710000,1006.94
3,2010-12,*Boombox Ipod Classic,1,16.980000,16.98
4,2010-12,*USB Office Mirror Ball,2,8.470000,16.94
5,2010-12,10 COLOUR SPACEBOY PEN,583,1.160811,525.27
6,2010-12,12 COLOURED PARTY BALLOONS,62,0.728750,40.93
7,2010-12,12 DAISY PEGS IN WOOD BOX,12,2.138571,23.22
8,2010-12,12 EGG HOUSE PAINTED WOOD,11,24.074444,254.91
9,2010-12,12 IVORY ROSE PEG PLACE SETTINGS,22,1.430000,28.76

In [27]:
# Rebuild monthly summary cleanly
monthly_summary = df.groupby(["MonthYear", "Description"], as_index=False).agg({
    "Quantity": "sum",
    "UnitPrice": "mean",
    "TotalSales": "sum"
})

monthly_summary.rename(columns={
    "Quantity": "TotalQuantitySold",
    "UnitPrice": "AverageUnitPrice"
}, inplace=True)

# Force numeric formatting
monthly_summary["AverageUnitPrice"] = monthly_summary["AverageUnitPrice"].astype(float).round(2)
monthly_summary["TotalSales"] = monthly_summary["TotalSales"].astype(float).round(2)

monthly_summary.head(10)

,MonthYear,Description,TotalQuantitySold,AverageUnitPrice,TotalSales
0,2010-12,4 PURPLE FLOCK DINNER CANDLES,16,3.39,45.82
1,2010-12,OVAL WALL MIRROR DIAMANTE,22,13.31,283.03
2,2010-12,SET 2 TEA TOWELS I LOVE LONDON,306,3.71,1006.94
3,2010-12,*Boombox Ipod Classic,1,16.98,16.98
4,2010-12,*USB Office Mirror Ball,2,8.47,16.94
5,2010-12,10 COLOUR SPACEBOY PEN,583,1.16,525.27
6,2010-12,12 COLOURED PARTY BALLOONS,62,0.73,40.93
7,2010-12,12 DAISY PEGS IN WOOD BOX,12,2.14,23.22
8,2010-12,12 EGG HOUSE PAINTED WOOD,11,24.07,254.91
9,2010-12,12 IVORY ROSE PEG PLACE SETTINGS,22,1.43,28.76

In [28]:
monthly_summary.to_csv("../data/processed/monthly_summary.csv", index=False)

print("Monthly summary re-exported successfully.")

Monthly summary re-exported successfully.